# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name: Install node dependencies
        run: |
          npm i
          npx cordova requirements

      # Supports one build per minute
      - name: Build AAB Bundle
        run: |
          set -e
          set -u
          echo "Update version number"
          export TIMESTAMP=$(( $(date '+%s%N') / 10000000000))
          sed -i "s/1.0.0/2.0.$TIMESTAMP/" config.xml
          echo "Build Cordova"
          npx cordova build android --prod

          echo "Build Android AAB Bundle"
          cd platforms/android && ./gradlew bundle
          
      - name: Signing APK and Bundle
        run: |
          git clone https://${{secrets.API_TOKEN_GITHUB}}:x-oauth-basic@github.com/${{secrets.KEYSTORE_REPO}}
          cd msahil432-play-keystore
          unzip -P ${{secrets.KEYSTORE_ZIP_PASSWORD}} temp.zip
          ls ./..
          ls ./../platforms/android/app/build/outputs
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore sahil432.jks ./../platforms/android/app/build/outputs/bundle/release/app-release.aab ${{secrets.KEYSTORE_KEY_VALUE}} -storepass ${{secrets.KEYSTORE_PASSWORD}}
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore sahil432.jks ./../platforms/android/app/build/outputs/apk/debug/app-debug.apk ${{secrets.KEYSTORE_KEY_VALUE}} -storepass ${{secrets.KEYSTORE_PASSWORD}}
          rm -rf ${{secrets.KEYSTORE_REPO}}

      - name: Creating Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.API_TOKEN_GITHUB}}"
          prerelease: false
          files: |
            ./platforms/android/app/build/outputs/bundle/release/app-release.aab
            ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
            
          
